//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
<<<<<<< HEAD
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milanov {
    
    
    public partial class Products1 {
        
        /// <summary>
        /// ListViewMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView ListViewMessage;
=======
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milanov
{


    public partial class Products1
    {
>>>>>>> origin/Yannick
    }
}
